[package]
name = "ddust1n/camerashaker"
description = "A fork of Sleitnick's RbxCameraShaker, fixed for wally."
license = "MIT"
version = "0.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
